name: Python Tests

on:
  push:
    branches:
      - main  # Trigger this on push to the `main` branch
  pull_request:
    branches:
      - main  # Trigger this on pull request to the `main` branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Upgrade pip
        pip install -r .github/requirements.txt  # Install project dependencies

    - name: Run tests with pytest
      run: |
        source venv/bin/activate  # Activate the virtual environment
        pytest  # Run the tests with pytest
